development:
  host: servername
  port: 636
  encryption: simple_tls
  auth:
      method: simple
      username: EXAMPLE_USERNAME
      password: EXAMPLE_PASSWORD

test:
  host: servername
  port: 636
  encryption: simple_tls
  auth:
      method: simple
      username: EXAMPLE_USERNAME
      password: EXAMPLE_PASSWORD

